### ISSUE TITLE
Timeout throwing an exception for something that has already been handled.

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#32]
[QueueListener Response Queue /services] DEBUG i.a.q.s.Server - Response not marked handled and it timed out, but could not be written io.advantageous.qbit.http.HttpRequest@87a022a3 
java.lang.IllegalStateException: Response has already been written
    at org.vertx.java.core.http.impl.DefaultHttpServerResponse.checkWritten(DefaultHttpServerResponse.java:452) ~[vertx-core-2.1.1.jar:na]
    at org.vertx.java.core.http.impl.DefaultHttpServerResponse.putHeader(DefaultHttpServerResponse.java:128) ~[vertx-core-2.1.1.jar:na]
    at org.vertx.java.core.http.impl.DefaultHttpServerResponse.putHeader(DefaultHttpServerResponse.java:39) ~[vertx-core-2.1.1.jar:na]
    at io.advantageous.qbit.vertx.http.HttpServerVertx.lambda$createResponse$13(HttpServerVertx.java:184) ~[qbit-vertx/:na]
    at io.advantageous.qbit.vertx.http.HttpServerVertx$$Lambda$15/289205234.response(Unknown Source) ~[na:na]
    at io.advantageous.qbit.server.Server.handleMethodTimedOut(Server.java:504) [qbit-boon/:na]
    at io.advantageous.qbit.server.Server.checkTimeoutsForRequests(Server.java:475) [qbit-boon/:na]
    at io.advantageous.qbit.server.Server.access$200(Server.java:39) [qbit-boon/:na]
    at io.advantageous.qbit.server.Server$1.idle(Server.java:268) [qbit-boon/:na]

**Comment by tausif-citrusPay** [comment]
Has this been resolved? I am facing this issue and don't know how to resolve.

**Comment by RichardHightower** [comment]
I was able to resolve this. It could be that you are running into in another scenario which could be a bug or could be not using the API as expected. Can you create small test case that reproduces the bug? And the issue a PR with said test case.

**Comment by tausif-citrusPay** [comment]
HI Richard,
Thanks for your prompt reply. After debugging in my code I found that using "context.next()" is causing the issue. Since "context.next" ends the  context and if we write response into context somewhere else in the code the exception will occur.For example

`Class Test {
function test_1(){
// some code
context.next();
}
function test_2(){
result = some_code;
context.response().end(result);

}`

**Comment by RichardHightower** [comment]
Context? context.next()... Not sure any of this is QBit.
