### ISSUE TITLE
If Boon parser craps out, qbit permahangs the request.

### ISSUE THREAD

**Issue by revelfire** [advantageous/qbit#352]
http://localhost:6060/user/create

{ deviceId: 'zxcv1234' }

result:

The below shows in the logs but the server never returns. Request just hangs.

2015-08-13 11:12:08,044 [vert.x-eventloop-thread-1] DEBUG io.advantageous.qbit.vertx.http.server.HttpServerVertx - HttpServerVertx::handleHttpRequest::PUT:/user/create
HttpServer::handleRequest HttpRequest{uri='/user/create', remoteAddress='/0:0:0:0:0:0:0:1:52289', params=io.advantageous.qbit.util.MultiMap$1@6e0801cc, headers=Vertx MultiMap Wrapper [Origin=chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm, Cookie=jwplayer.mute=false; jwplayer.volume=56; current-user=%7B%22token%22%3A%222136da5e-5f67-41e3-9624-97b206886b01%22%2C%22secret%22%3A%22ThDjfj9sB4suaETkuUQg%22%2C%22email%22%3A%22cgonzalez%2Bmoomoomoo%40softworx.org%22%2C%22merchantID%22%3A%2214971%22%2C%22moment%22%3A%222015-07-27T18%3A05%3A40.740Z%22%2C%22isValid%22%3Atrue%7D; stv="1434202105980,bbcd466d-ca09-4a6f-8f66-ba2f0ac9d28e,83"; JSESSIONID=F7206E909334BD7F2AADA6C73CB2D826, Accept=application/json, Cache-Control=no-cache, Connection=keep-alive, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36, Host=localhost:6060, Accept-Encoding=gzip, deflate, sdch, Accept-Language=en-US,en;q=0.8, Content-Length=24, Content-Type=application/json]
, body=[123, 32, 100, 101, 118, 105, 99, 101, 73, 100, 58, 32, 39, 122, 120, 99, 118, 49, 50, 51, 52, 39, 32, 125], contentType='application/json', method='PUT', receiver=io.advantageous.qbit.vertx.http.server.VertxServerUtils$1@30b5d7ab, messageId=8, timestamp=1439489528027, handled=false}
2015-08-13 11:12:08,045 [vert.x-eventloop-thread-1] DEBUG io.advantageous.qbit.http.server.impl.SimpleHttpServer - HttpServer::handleRequestHttpRequest{uri='/user/create', remoteAddress='/0:0:0:0:0:0:0:1:52289', params=io.advantageous.qbit.util.MultiMap$1@6e0801cc, headers=Vertx MultiMap Wrapper [Origin=chrome-extension://fdmmgilgnpjigdojojpjoooidkmcomcm, Cookie=jwplayer.mute=false; jwplayer.volume=56; current-user=%7B%22token%22%3A%222136da5e-5f67-41e3-9624-97b206886b01%22%2C%22secret%22%3A%22ThDjfj9sB4suaETkuUQg%22%2C%22email%22%3A%22cgonzalez%2Bmoomoomoo%40softworx.org%22%2C%22merchantID%22%3A%2214971%22%2C%22moment%22%3A%222015-07-27T18%3A05%3A40.740Z%22%2C%22isValid%22%3Atrue%7D; stv="1434202105980,bbcd466d-ca09-4a6f-8f66-ba2f0ac9d28e,83"; JSESSIONID=F7206E909334BD7F2AADA6C73CB2D826, Accept=application/json, Cache-Control=no-cache, Connection=keep-alive, User-Agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36, Host=localhost:6060, Accept-Encoding=gzip, deflate, sdch, Accept-Language=en-US,en;q=0.8, Content-Length=24, Content-Type=application/json]
, body=[123, 32, 100, 101, 118, 105, 99, 101, 73, 100, 58, 32, 39, 122, 120, 99, 118, 49, 50, 51, 52, 39, 32, 125], contentType='application/json', method='PUT', receiver=io.advantageous.qbit.vertx.http.server.VertxServerUtils$1@30b5d7ab, messageId=8, timestamp=1439489528027, handled=false}
Aug 13, 2015 11:12:08 AM org.vertx.java.core.logging.impl.JULLogDelegate error
SEVERE: Unhandled exception
io.advantageous.boon.json.JsonException: expecting '}' or ',' but got current char 'd' with an int value of 100

The current character read is 'd' with an int value of 100
expecting '}' or ',' but got current char 'd' with an int value of 100
line number 1
index number 2
{ deviceId: 'zxcv1234' }
..^
	at io.advantageous.boon.json.implementation.JsonParserCharArray.complain(JsonParserCharArray.java:190)
	at io.advantageous.boon.json.implementation.JsonFastParser.decodeJsonObjectLazyFinalParse(JsonFastParser.java:126)
	at io.advantageous.boon.json.implementation.JsonFastParser.decodeValueOverlay(JsonFastParser.java:144)
	at io.advantageous.boon.json.implementation.JsonFastParser.parse(JsonFastParser.java:328)
	at io.advantageous.boon.json.implementation.BaseJsonParser.parse(BaseJsonParser.java:126)
	at io.advantageous.boon.json.implementation.BaseJsonParserAndMapper.parse(BaseJsonParserAndMapper.java:766)
	at io.advantageous.qbit.BoonJsonMapper.fromJsonMap(BoonJsonMapper.java:106)
	at io.advantageous.qbit.meta.transformer.StandardRequestTransformer.transform(StandardRequestTransformer.java:193)
	at io.advantageous.qbit.server.HttpRequestServiceServerHandlerUsingMetaImpl.handleRestCall(HttpRequestServiceServerHandlerUsingMetaImpl.java:105)
	at io.advantageous.qbit.server.ServiceEndpointServerImpl$$Lambda$34/170052458.accept(Unknown Source)
	at io.advantageous.qbit.http.server.impl.SimpleHttpServer.handleRequest(SimpleHttpServer.java:88)
	at io.advantageous.qbit.vertx.http.server.HttpServerVertx.lambda$handleHttpRequest$14(HttpServerVertx.java:225)
	at io.advantageous.qbit.vertx.http.server.HttpServerVertx$$Lambda$48/655982591.handle(Unknown Source)
	at org.vertx.java.core.http.impl.DefaultHttpServerRequest$2.handle(DefaultHttpServerRequest.java:228)
	at org.vertx.java.core.VoidHandler.handle(VoidHandler.java:27)
	at org.vertx.java.core.VoidHandler.handle(VoidHandler.java:24)
	at org.vertx.java.core.http.impl.DefaultHttpServerRequest.handleEnd(DefaultHttpServerRequest.java:314)
	at org.vertx.java.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:209)
	at org.vertx.java.core.http.impl.ServerConnection.processMessage(ServerConnection.java:313)
	at org.vertx.java.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:94)
	at org.vertx.java.core.http.impl.DefaultHttpServer$ServerHandler.doMessageReceived(DefaultHttpServer.java:703)
	at org.vertx.java.core.http.impl.DefaultHttpServer$ServerHandler.doMessageReceived(DefaultHttpServer.java:593)
	at org.vertx.java.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:63)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:156)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Aug 13, 2015 11:12:08 AM org.vertx.java.core.logging.impl.JULLogDelegate error
SEVERE: Unhandled exception
io.advantageous.boon.json.JsonException: expecting '}' or ',' but got current char 'd' with an int value of 100

The current character read is 'd' with an int value of 100
expecting '}' or ',' but got current char 'd' with an int value of 100
line number 1
index number 2
{ deviceId: 'zxcv1234' }
..^
	at io.advantageous.boon.json.implementation.JsonParserCharArray.complain(JsonParserCharArray.java:190)
	at io.advantageous.boon.json.implementation.JsonFastParser.decodeJsonObjectLazyFinalParse(JsonFastParser.java:126)
	at io.advantageous.boon.json.implementation.JsonFastParser.decodeValueOverlay(JsonFastParser.java:144)
	at io.advantageous.boon.json.implementation.JsonFastParser.parse(JsonFastParser.java:328)
	at io.advantageous.boon.json.implementation.BaseJsonParser.parse(BaseJsonParser.java:126)
	at io.advantageous.boon.json.implementation.BaseJsonParserAndMapper.parse(BaseJsonParserAndMapper.java:766)
	at io.advantageous.qbit.BoonJsonMapper.fromJsonMap(BoonJsonMapper.java:106)
	at io.advantageous.qbit.meta.transformer.StandardRequestTransformer.transform(StandardRequestTransformer.java:193)
	at io.advantageous.qbit.server.HttpRequestServiceServerHandlerUsingMetaImpl.handleRestCall(HttpRequestServiceServerHandlerUsingMetaImpl.java:105)
	at io.advantageous.qbit.server.ServiceEndpointServerImpl$$Lambda$34/170052458.accept(Unknown Source)
	at io.advantageous.qbit.http.server.impl.SimpleHttpServer.handleRequest(SimpleHttpServer.java:88)
	at io.advantageous.qbit.vertx.http.server.HttpServerVertx.lambda$handleHttpRequest$14(HttpServerVertx.java:225)
	at io.advantageous.qbit.vertx.http.server.HttpServerVertx$$Lambda$48/655982591.handle(Unknown Source)
	at org.vertx.java.core.http.impl.DefaultHttpServerRequest$2.handle(DefaultHttpServerRequest.java:228)
	at org.vertx.java.core.VoidHandler.handle(VoidHandler.java:27)
	at org.vertx.java.core.VoidHandler.handle(VoidHandler.java:24)
	at org.vertx.java.core.http.impl.DefaultHttpServerRequest.handleEnd(DefaultHttpServerRequest.java:314)
	at org.vertx.java.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:209)
	at org.vertx.java.core.http.impl.ServerConnection.processMessage(ServerConnection.java:313)
	at org.vertx.java.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:94)
	at org.vertx.java.core.http.impl.DefaultHttpServer$ServerHandler.doMessageReceived(DefaultHttpServer.java:703)
	at org.vertx.java.core.http.impl.DefaultHttpServer$ServerHandler.doMessageReceived(DefaultHttpServer.java:593)
	at org.vertx.java.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:63)
	at org.vertx.java.core.net.impl.VertxHandler.channelRead(VertxHandler.java:156)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:332)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

@RequestMapping("/user")
public class ProvisioningController extends BaseController {

    private final UserService userService;

    public ProvisioningController() {
        userService = new UserService();
    }

    private static final String REQUEST_MAP_DEVICE_ID = "deviceId";

    @RequestMapping(value = "/create", method={RequestMethod.PUT})
    public ApiResponse provision(Map<String, String> request) {
        try {
            return new ApiResponse(userService.createNewUser(request.get(REQUEST_MAP_DEVICE_ID)));
        } catch (Exception e) {
            return new ApiResponse(ApiError.PROVISIONING_FAILED);
        }
    }

}

**Comment by revelfire** [comment]
Worth noting that single quotes appears to be the devil.  Too many bad habits from JS and Mongo use.

{ "deviceId": "zxcv1234" }

In any case the server should probably throw some sort of 'malformed json' error.

**Comment by RichardHightower** [comment]
I agree.

On Thu, Aug 13, 2015 at 11:17 AM, revelfire <notifications@github.com>
wrote:

> Worth noting that single quotes appears to be the devil. Too many bad
> habits from JS and Mongo use.
>
> { "deviceId": "zxcv1234" }
>
> In any case the server should probably throw some sort of 'malformed json'
> error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/352#issuecomment-130787080>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by RichardHightower** [comment]
Fixed https://github.com/advantageous/qbit/commit/9b9fd6cf52cf20168abdf1a9778e4adb4e3287c9

**Comment by RichardHightower** [comment]
Please try it out and repoen if not actually fixed.

**Comment by RichardHightower** [comment]
Ok. I assume you are getting the same error.

You tried the snapshot?

On Thursday, August 13, 2015, revelfire <notifications@github.com> wrote:

> Reopened #352 <https://github.com/advantageous/qbit/issues/352>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/352#event-382236133>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by revelfire** [comment]
Solid!

**Comment by revelfire** [comment]
No I suck at bringing in upstream changes. s'all good.

**Comment by RichardHightower** [comment]
Oh thank the Lord. I thought I reproduced and fixed it. I was pulling my
imaginary hair out.

On Thursday, August 13, 2015, revelfire <notifications@github.com> wrote:

> No I suck at bringing in upstream changes. s'all good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/advantageous/qbit/issues/352#issuecomment-130978979>.
>


-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>
