### ISSUE TITLE
How to use getWith1ParamWithTimeout

### ISSUE THREAD

**Issue by ArcosBinary** [advantageous/qbit#378]
Hey,

I  want to use a timeout for my http request like this:

```Java
HttpResponse with1Param = httpClient.getWith1ParamWithTimeout(
				"/services/transition-service/setTransition",
				"transitionString", JsonFactory.toJson(transition),2,TimeUnit.SECONDS);

System.out.println("GOT: "+with1Param.body());
```
My problem: when I'm disabling my service to test the timeout, the timeout doesn't work. 
After 2 seconds my syso isn't called. 
What is necassary to make my httpClient return false after 2 seconds?

Thanks in advance!

**Comment by RichardHightower** [comment]
Looks like you are using it correctly. 
Could be a bug.

**Comment by RichardHightower** [comment]
Either I fixed this and forgot. Somewhat likely. Or it is not a bug, or I am not reproducing it well.


```java
package io.advantageous.qbit.example.httpclient;

import io.advantageous.qbit.http.request.HttpTextResponse;
import io.advantageous.qbit.http.server.HttpServer;

import io.advantageous.qbit.http.client.HttpClient;

import java.util.concurrent.TimeUnit;

import static io.advantageous.qbit.http.server.HttpServerBuilder.httpServerBuilder;

import static io.advantageous.qbit.http.client.HttpClientBuilder.httpClientBuilder;

public class HttpClientExample {


    public static void main(final String... args) {

        final HttpServer httpServer = httpServerBuilder().build();
        httpServer.setHttpRequestConsumer(request -> {
            if (request.getParams().getFirst("myparam").equals("myvalue")) {
                request.getReceiver().respondOK("\"hello\"");
            }
        });

        httpServer.startServerAndWait(); //starts and wait until server is listening


        final HttpClient client = httpClientBuilder().buildAndStart();

        final HttpTextResponse with1ParamWithTimeout = client.getWith1ParamWithTimeout("/", "myparam", "myvalue", 1, TimeUnit.SECONDS);

        System.out.println(with1ParamWithTimeout.body());

        final HttpTextResponse with1ParamWithTimeout2 = client.getWith1ParamWithTimeout("/", "myparam", "sdf", 1, TimeUnit.SECONDS);


        System.out.println(with1ParamWithTimeout2.body());
    }

}

```

The above works

```sh
"hello"
Exception in thread "main" io.advantageous.qbit.http.client.HttpClientTimeoutException: Timeout start time Fri Dec 04 14:57:12 PST 2015 now Fri Dec 04 14:57:14 PST 2015
	at io.advantageous.qbit.http.client.HttpClient.sendRequestAndWait(HttpClient.java:417)
	at io.advantageous.qbit.http.client.HttpClient.getWith1ParamWithTimeout(HttpClient.java:468)
	at io.advantageous.qbit.example.httpclient.HttpClientExample.main(HttpClientExample.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 130

```
