### ISSUE TITLE
ClassCastException: Starting Admin  - 0.9.0-RC1

### ISSUE THREAD

**Issue by thorcode** [advantageous/qbit#382]
Working through the following turorial - Getting started with QBit Microservices Lib Batteries Included Part 2

````java
public static void main(String... args) {
        final ManagedServiceBuilder managedServiceBuilder = ManagedServiceBuilder.managedServiceBuilder().setRootURI("/root");
        managedServiceBuilder.addEndpointService(new CodeGeneratorService()).getEndpointServerBuilder().build().startServer();
        managedServiceBuilder.getAdminBuilder().build().startServer();
    }
````

Blows up on managedServiceBuilder.getAdminBuilder().build().startServer();

Admin.getSystemProperties() returns java.util.Properties and Map.class.isAssignableFrom(Properties.class) is true but....  Unless I am missing something.... I don't believe that Properties genericReturnTypes() is going to return back a ParameterizedType as Properties doesn't have type params.  Images below.

Exception in thread "main" java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
	at io.advantageous.qbit.meta.builder.ServiceMethodMetaBuilder.deduceReturnTypes(ServiceMethodMetaBuilder.java:162)
	at io.advantageous.qbit.meta.builder.ServiceMethodMetaBuilder.build(ServiceMethodMetaBuilder.java:131)
	at io.advantageous.qbit.meta.builder.ServiceMetaBuilder.addMethod(ServiceMetaBuilder.java:139)
	at io.advantageous.qbit.meta.builder.ServiceMetaBuilder.lambda$addMethods$38(ServiceMetaBuilder.java:103)
	at io.advantageous.qbit.meta.builder.ServiceMetaBuilder$$Lambda$3/226710952.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at io.advantageous.qbit.meta.builder.ServiceMetaBuilder.addMethods(ServiceMetaBuilder.java:103)
	at io.advantageous.qbit.meta.builder.ContextMetaBuilder.addService(ContextMetaBuilder.java:316)
	at io.advantageous.qbit.server.HttpRequestServiceServerHandlerUsingMetaImpl.addRestSupportFor(HttpRequestServiceServerHandlerUsingMetaImpl.java:166)
	at io.advantageous.qbit.server.ServiceEndpointServerImpl.initServices(ServiceEndpointServerImpl.java:388)
	at io.advantageous.qbit.admin.AdminBuilder.build(AdminBuilder.java:374)

![image](https://cloud.githubusercontent.com/assets/4273886/9696492/905b3b92-533e-11e5-83b8-40a7b5bd23a8.png)

![image](https://cloud.githubusercontent.com/assets/4273886/9696502/be4347ac-533e-11e5-8564-d5f75f81222d.png)

java.runtime.version=1.8.0_25-b18
WIndoze 10 Pro
x64

**Comment by thorcode** [comment]
Reverted qbit-admin-0.8.19-RC2 and it worked fine... 

$ curl http://localhost:7777/__admin/meta/
{"swagger":"2.0","info":{"title":"application title goes here","description":"Description not set","contact":{"name":"ContactName not set","url":"Contact URL not set","email":"no.contact.email@set.me.please.com"},"version":"0.1-NOT-SET","license":{"name":"licenseName not set","url":"http://www.license.url.com/not/set/"}},"host":"localhost:8080","basePath":"/root","schemes":["http","https","wss","ws"],"consumes":["application/json"],"produces":["application/json"],"paths":{"generator/ping":{"get":{"operationId":"hello","summary":"no summary","description":"no description","produces":["application/json"],"responses":{"200":{"description":"no return description","schema":{"type":"string"}}}}},"generator/randomCode":{"get":{"operationId":"randomCode","summary":"no summary","description":"no description","produces":["application/json"],"responses":{"200":{"description":"no return description","schema":{"type":"array","items":{"type":"string","format":"byte"}}}}}}}}

**Comment by RichardHightower** [comment]
Cool. I switched to map to add a black list for password system properties.

**Comment by RichardHightower** [comment]
Thanks for the report. :)
