### ISSUE TITLE
Concurrent Mod Exception in Stats

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#456]
```java
java.util.ConcurrentModificationException: null
	at java.util.HashMap$Values.forEach(HashMap.java:975) ~[na:1.8.0_45]
	at io.advantageous.qbit.service.stats.StatsCollectorBuffer.sendStats(StatsCollectorBuffer.java:104) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.service.stats.StatsCollectorBuffer.clientProxyFlush(StatsCollectorBuffer.java:135) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.service.stats.ServiceStatsListener.flushStatsIfNeeded(ServiceStatsListener.java:206) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.service.stats.ServiceStatsListener.sendStats(ServiceStatsListener.java:151) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.service.stats.ServiceStatsListener.queueIdle(ServiceStatsListener.java:136) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.queue.QueueCallBackHandlerHub.queueIdle(QueueCallBackHandlerHub.java:56) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.service.impl.BaseServiceQueueImpl$3.idle(BaseServiceQueueImpl.java:467) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.queue.impl.BasicReceiveQueueManager.manageQueue(BasicReceiveQueueManager.java:120) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.queue.impl.BasicQueue.manageQueue(BasicQueue.java:202) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.queue.impl.BasicQueue.lambda$startListener$46(BasicQueue.java:173) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.queue.impl.BasicQueue$$Lambda$9/1308109015.run(Unknown Source) ~[na:na]
	at io.advantageous.qbit.concurrent.ScheduledThreadContext.lambda$start$16(ScheduledThreadContext.java:89) ~[qbit-core-0.9.1-RC2.jar:na]
	at io.advantageous.qbit.concurrent.ScheduledThreadContext$$Lambda$4/1188753216.run(Unknown Source) [qbit-core-0.9.1-RC2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by RichardHightower** [comment]
I think this is a matter of using the API incorrectly, but I am withholding judgement.

**Comment by RichardHightower** [comment]
Operator error. Confirmed with test and code review
