### ISSUE TITLE
qbit does not run on OpenJDK 1.8.0

### ISSUE THREAD

**Issue by mailq** [advantageous/qbit#473]
When trying a HelloWorld example for evaluating qbit I get a NumberFormatException:

java.lang.NumberFormatException: For input string: "45-internal"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at io.advantageous.boon.core.Sys.<clinit>(Sys.java:102)
	at io.advantageous.boon.core.reflection.Reflection.<clinit>(Reflection.java:114)
	at io.advantageous.boon.core.reflection.ClassMeta.classMeta(ClassMeta.java:271)
	at io.advantageous.qbit.QBit.registerReflectionAndJsonParser(QBit.java:69)
	at io.advantageous.qbit.QBit.doGetFactory(QBit.java:58)
	at io.advantageous.qbit.QBit.factory(QBit.java:46)
	at io.advantageous.qbit.http.server.HttpServerBuilder.getFactory(HttpServerBuilder.java:121)
	at io.advantageous.qbit.http.server.HttpServerBuilder.build(HttpServerBuilder.java:257)
	at HelloWorldRestServer.main(HelloWorldRestServer.java:18)
Unable to determine build number or version

This is because I am running on Ubuntu 14.04 with their "official" OpenJDK 1.8.0. The Ubuntu version has a java.version=1.8.0_45-internal. The qbit code tries to parse "45-internal" into an Integer, which isn't an integer.

The expected behavior is "just work", as it is a standard and compatible Java 8 JRE: http://packages.ubuntu.com/en/vivid/java/openjdk-8-jre

I have not investigated "why" the build version is needed. If the version number does not match, it is set to -1 anyway. So either make it "just work" with OpenJDK or set the build version to -1.

**Comment by RichardHightower** [comment]
it is just a warning. It still runs.

**Comment by mailq** [comment]
After your comment I investigated further. The problem is not the NumberFormatException. The follow-up NullPointerException (leading to a graceful stop) occurs not because of the pre NumberFormatException, but a dependency injection problem.
The HelloWorld needs the qbit-vertx dependency to run as expected. Now everything is fine (except the logging of the ignorable NumberFormatException)
This issue can/should be closed, if you are not going to transform this exception into a warning/info message.

**Comment by RichardHightower** [comment]
thanks for the follow up... NumberFormatException exception is lame.. I plan on getting rid of it soon.
