### ISSUE TITLE
QBit countDown System

### ISSUE THREAD

**Issue by RichardHightower** [advantageous/qbit#671]
This happens in a project in a test I am working on.

Tests pass.

But still

```

:testException in thread "Thread-42" java.lang.IllegalArgumentException: count < 0
	at java.util.concurrent.CountDownLatch.<init>(CountDownLatch.java:199)
	at io.advantageous.qbit.system.QBitSystemManager.waitForShutdown(QBitSystemManager.java:169)
	at io.advantageous.qbit.system.QBitSystemManager$1.run(QBitSystemManager.java:64)
:check
```

**Comment by RichardHightower** [comment]
user error
